import { Dimensions, StyleSheet } from "react-native";
const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;
export const AuthEmailScreenStyles =  StyleSheet.create({
   container: {
        flex: 1,
        backgroundColor: '#f0f4f8',
        position: 'relative',
        overflow: 'hidden',
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        zIndex: 10,
        padding: 20,
    },
    circle1: {
        position: 'absolute',
        width: screenWidth * 0.8,
        height: screenWidth * 0.8,
        borderRadius: screenWidth * 0.4,
        backgroundColor: 'rgba(106, 90, 224, 0.1)',
        top: -screenWidth * 0.2,
        left: -screenWidth * 0.15,
        zIndex: 1,
        shadowColor: 'rgba(106, 90, 224, 0.2)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    circle2: {
        position: 'absolute',
        width: screenWidth * 0.6,
        height: screenWidth * 0.6,
        borderRadius: screenWidth * 0.3,
        backgroundColor: 'rgba(106, 90, 224, 0.09)',
        bottom: -screenWidth * 0.1,
        right: -screenWidth * 0.1,
        zIndex: 1,
        shadowColor: 'rgba(106, 90, 224, 0.2)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    circle3: {
        position: 'absolute',
        width: screenWidth * 0.5,
        height: screenWidth * 0.5,
        borderRadius: screenWidth * 0.25,
        backgroundColor: 'rgba(106, 90, 224, 0.08)',
        top: screenHeight * 0.25,
        right: -screenWidth * 0.1,
        zIndex: 1,
        shadowColor: 'rgba(106, 90, 224, 0.2)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    circle4: {
        position: 'absolute',
        width: screenWidth * 0.4,
        height: screenWidth * 0.4,
        borderRadius: screenWidth * 0.2,
        backgroundColor: 'rgba(106, 90, 224, 0.07)',
        bottom: screenHeight * 0.15,
        left: -screenWidth * 0.05,
        zIndex: 1,
        shadowColor: 'rgba(106, 90, 224, 0.2)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    circle5: {
        position: 'absolute',
        width: screenWidth * 0.3,
        height: screenWidth * 0.3,
        borderRadius: screenWidth * 0.15,
        backgroundColor: 'rgba(106, 90, 224, 0.06)',
        top: screenHeight * 0.4,
        left: screenWidth * 0.4,
        zIndex: 1,
        shadowColor: 'rgba(106, 90, 224, 0.2)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    triangle: {
        position: 'absolute',
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderRightWidth: screenWidth * 0.3,
        borderTopWidth: screenWidth * 0.3,
        borderRightColor: 'transparent',
        borderTopColor: 'rgba(106, 90, 224, 0.09)',
        top: screenHeight * 0.1,
        right: screenWidth * 0.05,
        transform: [{ rotate: '45deg' }],
        zIndex: 1,
        shadowColor: 'rgba(106, 90, 224, 0.2)',
        shadowOffset: { width: 4, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    square: {
        position: 'absolute',
        width: screenWidth * 0.25,
        height: screenWidth * 0.25,
        backgroundColor: 'rgba(106, 90, 224, 0.08)',
        transform: [{ rotate: '15deg' }],
        bottom: screenHeight * 0.1,
        left: screenWidth * 0.05,
        zIndex: 1,
        shadowColor: 'rgba(106, 90, 224, 0.2)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    
})