import { StyleSheet } from "react-native";
import { ColorTheme } from "../../../../style/Colors";

export const RecordCreateFormStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: ColorTheme.back_color,
    },
    scrollContent: {
        padding: 25,
        paddingBottom: 50,
    },
    titleContainer: {
        marginBottom: 30,
        paddingBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: ColorTheme.gray_light,
    },
    title: {
        fontSize: 28,
        fontWeight: '800',
        color: ColorTheme.main_color,
        textAlign: 'center',
        marginTop: 20,
        textShadowColor: 'rgba(119, 72, 229, 0.1)',
        textShadowOffset: {width: 0, height: 2},
        textShadowRadius: 4,
    },
    titleSub: {
        fontSize: 16,
        color: ColorTheme.gray_dark,
        textAlign: 'center',
        marginTop: 8,
    },
    inputContainer: {
        marginBottom: 15,
        position: 'relative',
    },
    distortionContainer: {
        marginBottom: 20,
        marginTop: 15,
    },
    label: {
        fontSize: 16,
        fontWeight: '700',
        color: ColorTheme.gray_dark,
        marginBottom: 12,
        paddingLeft: 8,
        borderLeftWidth: 3,
        borderLeftColor: ColorTheme.main_light,
    },
    input: {
        backgroundColor: 'white',
        borderRadius: 14,
        padding: 18,
        fontSize: 16,
        color: ColorTheme.gray_dark,
        minHeight: 150,
        textAlignVertical: 'top',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        shadowColor: '#d1d5db',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    inputFocused: {
        borderColor: ColorTheme.main_light,
        shadowColor: ColorTheme.main_light,
        shadowOpacity: 0.2,
    },
    inputError: {
        borderColor: ColorTheme.error,
        backgroundColor: '#fff0f0',
    },
    errorText: {
        color: ColorTheme.error,
        fontSize: 14,
        marginTop: 8,
        marginLeft: 5,
    },
    distortionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: 14,
        padding: 18,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        shadowColor: '#d1d5db',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    distortionIcon: {
        marginRight: 12,
        backgroundColor: ColorTheme.main_light + '20',
        borderRadius: 10,
        padding: 8,
    },
    distortionButtonText: {
        flex: 1,
        fontSize: 16,
        color: ColorTheme.gray_dark,
        fontWeight: '500',
    },
    selectedContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 15,
    },
    selectedTag: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: ColorTheme.main_color,
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 15,
        marginRight: 10,
        marginBottom: 10,
        shadowColor: ColorTheme.main_color,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 2,
    },
    selectedTagText: {
        color: 'white',
        fontSize: 14,
        marginRight: 8,
        fontWeight: '500',
    },
    tagClose: {
        backgroundColor: 'rgba(255,255,255,0.3)',
        borderRadius: 10,
        width: 22,
        height: 22,
        justifyContent: 'center',
        alignItems: 'center',
    },
    submitButton: {
        borderRadius: 14,
        padding: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
        shadowColor: ColorTheme.main_color,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 8,
    },
    submitButtonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    serverError: {
        color: ColorTheme.error,
        textAlign: 'center',
        marginTop: 20,
        fontSize: 15,
        fontWeight: '500',
        padding: 12,
        backgroundColor: '#fff0f0',
        borderRadius: 10,
    },
    sectionDivider: {
        height: 1,
        backgroundColor: ColorTheme.gray_light,
        marginVertical: 30,
        marginHorizontal: 10,
    },
    iconContainer: {
        position: 'absolute',
        right: 15,
        top: 15,
        zIndex: 10,
    }
})